name: Test and Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

job:
  build:
    name: Build Env
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go
          with:
            go-version: '1.14'
          id: go

      - name: Checkout App
        uses: actions/checkout@v2

      - name: Build App
        run: go test -run driver_test.go